### ISSUE TITLE
Update query from the documentation not working

### ISSUE THREAD

**Issue by imbdb** [neo4j/driver-documentation#408]
I am trying to use neo4j driver in my typescript project and while trying query from documentation [here](https://neo4j.com/docs/javascript-manual/current/query-simple/#_update_the_database), I encountered below mentioned syntax error.

Details
Neo4j version: `neo4j:4.0` (Docker Compose)
Neo4j Driver npm version:  `5.14.0`

**Sample code**
```typescript
import neo4j from "neo4j-driver";
import dotenv from "dotenv";
dotenv.config();

const driver = neo4j.driver(
  "bolt://localhost",
  neo4j.auth.basic(process.env.NEO4J_USER ?? "", process.env.NEO4J_PASS ?? "")
);

export async function getDriver() {
  const info = await driver.getServerInfo();
  console.log("Connected to Neo4j");
  console.log(info);
  return driver;
}

(async () => {
  const driver = await getDriver();
  const { summary } = await driver.executeQuery(
    `
  MATCH (p:Person WHERE p.name = $name)
  SET p.age = $age
  `,
    { name: "Alice", age: 42 }
  );
  console.log("Query counters:");
  console.log(summary.counters.updates());
})();

```

**Error**

```shell
> server@1.0.0 dev /app/server
> ts-node app.ts

Connected to Neo4j
ServerInfo {
  address: 'localhost:7687',
  agent: 'Neo4j/4.0.12',
  protocolVersion: 3
}
/app/server/node_modules/.pnpm/neo4j-driver-core@5.14.0/node_modules/neo4j-driver-core/lib/result.js:613
    var error = new Error('');
                ^
Neo4jError: Invalid input 'W': expected whitespace, comment, NodeLabel, MapLiteral, a parameter, a parameter (old syntax), ')' or a relationship pattern (line 2, column 17 (offset: 19))
"  MATCH (p:Person WHERE p.name = $name)"
                   ^

    at captureStacktrace (/app/server/node_modules/.pnpm/neo4j-driver-core@5.14.0/node_modules/neo4j-driver-core/lib/result.js:613:17)
    at new Result (/app/server/node_modules/.pnpm/neo4j-driver-core@5.14.0/node_modules/neo4j-driver-core/lib/result.js:105:23)
    at newCompletedResult (/app/server/node_modules/.pnpm/neo4j-driver-core@5.14.0/node_modules/neo4j-driver-core/lib/transaction.js:520:12)
    at Object.run (/app/server/node_modules/.pnpm/neo4j-driver-core@5.14.0/node_modules/neo4j-driver-core/lib/transaction.js:352:20)
    at TransactionPromise.Transaction.run (/app/server/node_modules/.pnpm/neo4j-driver-core@5.14.0/node_modules/neo4j-driver-core/lib/transaction.js:183:34)
    at ManagedTransaction.run (/app/server/node_modules/.pnpm/neo4j-driver-core@5.14.0/node_modules/neo4j-driver-core/lib/transaction-managed.js:56:21)
    at QueryExecutor.<anonymous> (/app/server/node_modules/.pnpm/neo4j-driver-core@5.14.0/node_modules/neo4j-driver-core/lib/internal/query-executor.js:87:57)
    at step (/app/server/node_modules/.pnpm/neo4j-driver-core@5.14.0/node_modules/neo4j-driver-core/lib/internal/query-executor.js:51:23)
    at Object.next (/app/server/node_modules/.pnpm/neo4j-driver-core@5.14.0/node_modules/neo4j-driver-core/lib/internal/query-executor.js:32:53)
    at /app/server/node_modules/.pnpm/neo4j-driver-core@5.14.0/node_modules/neo4j-driver-core/lib/internal/query-executor.js:26:71 {
  constructor: [Function: Neo4jError] { isRetriable: [Function (anonymous)] },
  code: 'Neo.ClientError.Statement.SyntaxError',
  retriable: false
}
```

**Comment by stefano-ottolenghi** [comment]
Thanks for raising this. The issue is that the syntax `(:Person WHERE ...)` is only available in Neo4j v5. Given that drivers v5 are backwards compatible, it makes sense to avoid Cypher syntax unavailable in v4 even in the driver manuals for v5. I've now tweaked that example https://github.com/neo4j/docs-drivers/commit/534aa1be48eac0938753319cbada1081372c1723 , it will be live shortly.
